In [1]:
import pandas as pd
import os
import numpy as np
import datetime as dt
import sqlalchemy
from sqlalchemy import create_engine
from secrets import username, password
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# UN Data #

In [2]:
# load un_govt.csv
un_govt= pd.read_csv("./data/un_govt.csv")
un_govt

,Unnamed: 0,country,population_2020,constitutional_form,head_of_state,basis_of_executive_legitimacy,id
0,0,Afghanistan,39074280,Republic,Executive,Presidency is independent of legislature,30000
1,1,Albania,2877239,Republic,Ceremonial,Ministry is subject to parliamentary confidence,30001
2,2,Algeria,43984569,Republic,Executive,Presidency independent of legislature; ministr...,30002
3,3,Argentina,45267449,Republic,Executive,Presidency is independent of legislature,30003
4,4,Armenia,2964219,Republic,Ceremonial,Ministry is subject to parliamentary confidence,30004
...,...,...,...,...,...,...,...
131,136,Venezuela,28421581,Republic,Executive,Presidency is independent of legislature,30181
132,137,Vietnam,97490013,Republic,Executive,Power constitutionally linked to a single poli...,30182
133,138,Yemen,29935468,Provisional,No constitutionally-defined basis to current r...,No constitutionally-defined basis to current r...,30183
134,139,Zambia,18468257,Republic,Executive,Presidency is independent of legislature,30184
135,140,Zimbabwe,14899771,Republic,Executive,Presidency is independent of legislature,30185

In [3]:
un_govt = un_govt.drop(columns = ['Unnamed: 0'])

In [4]:
un_govt.dtypes

country                          object
population_2020                   int64
constitutional_form              object
head_of_state                    object
basis_of_executive_legitimacy    object
id                                int64
dtype: object

# happiness data #

In [5]:
# load world_happiness
world_happiness = "./data/world_happiness.csv"
world_happiness = pd.read_csv(world_happiness)
world_happiness

,Unnamed: 0,country_id,world_region,happiness_score,gdp_per_capita,social_support,healthy_life_expectancy,freedom_of_choice,generosity,perceptions_of_corruption,year_2020
0,0,30000,South Asia,2.5669,7.462861,0.470367,52.590000,0.396573,-0.096429,0.933687,2020-01-01
1,1,30001,Central and Eastern Europe,4.8827,9.417931,0.671070,68.708138,0.781994,-0.042309,0.896304,2020-01-01
2,2,30002,Middle East and North Africa,5.0051,9.537965,0.803385,65.905174,0.466611,-0.121105,0.735485,2020-01-01
3,3,30003,Latin America and Caribbean,5.9747,9.810955,0.900568,68.803802,0.831132,-0.194914,0.842010,2020-01-01
4,4,30004,Commonwealth of Independent States,4.6768,9.100476,0.757479,66.750656,0.712018,-0.138780,0.773545,2020-01-01
...,...,...,...,...,...,...,...,...,...,...,...
131,131,30181,Latin America and Caribbean,5.0532,8.977794,0.890408,66.505341,0.623278,-0.169091,0.837038,2020-01-01
132,132,30182,Southeast Asia,5.3535,8.809546,0.849987,67.952736,0.939593,-0.094533,0.796421,2020-01-01
133,133,30183,Middle East and North Africa,3.5274,7.759683,0.817981,56.727283,0.599920,-0.157735,0.800288,2020-01-01
134,134,30184,Sub-Saharan Africa,3.7594,8.224720,0.698824,55.299377,0.806500,0.078037,0.801290,2020-01-01
135,135,30185,Sub-Saharan Africa,3.2992,7.865712,0.763093,55.617260,0.711458,-0.072064,0.810237,2020-01-01

In [6]:
world_happiness = world_happiness.drop(columns = ['Unnamed: 0'])

In [7]:
world_happiness.dtypes

country_id                     int64
world_region                  object
happiness_score              float64
gdp_per_capita               float64
social_support               float64
healthy_life_expectancy      float64
freedom_of_choice            float64
generosity                   float64
perceptions_of_corruption    float64
year_2020                     object
dtype: object

# covid data #

In [8]:
# import csv as df

world_covid_data = pd.read_csv("./data/world_covid_data.csv")
world_covid_data.tail()

,Unnamed: 0,country_id,covid_cases_id,date,new_cases,new_deaths,extreme_poverty,handwashing_facilities,covid_times_life_expectancy
41669,41670,30185,59829.0,2020-06-20,0.0,0.0,21.4,36.791,61.49
41670,41671,30185,59830.0,2020-06-19,16.0,0.0,21.4,36.791,61.49
41671,41672,30185,59831.0,2020-06-18,62.0,0.0,21.4,36.791,61.49
41672,41673,30185,59832.0,2020-08-09,74.0,2.0,21.4,36.791,61.49
41673,41674,30185,59833.0,2020-12-31,242.0,3.0,21.4,36.791,61.49

In [9]:
world_covid_data = world_covid_data.drop(columns = ['Unnamed: 0'])

In [10]:
# look at types

world_covid_data.dtypes

country_id                       int64
covid_cases_id                 float64
date                            object
new_cases                      float64
new_deaths                     float64
extreme_poverty                float64
handwashing_facilities         float64
covid_times_life_expectancy    float64
dtype: object

# govt response data #

In [11]:
# Read csv and store in to Pandas Dataframe
gov_response = pd.read_csv('./data/gov_response.csv')
gov_response

,Unnamed: 0,response_id,gov_resp_desc,gov_resp_date,gov_resp_type,enforcer,gov_resp_link_src,country_id
0,0,300.0,"March 6, Afghanistan ""Measures have been taken...",2020-03-06,Anti-Disinformation Measures,"Ministry/Department of Health,Other",https://www.etilaatroz.com/94246/fears-rumors-...,30000
1,1,402.0,"""On 26 March, the President of Afghanistan, As...",2020-03-26,Other Policy Not Listed,National Governm,https://reliefweb.int/report/afghanistan/afgha...,30000
2,2,403.0,"In Afghanistan's ""eastern province of Nangarha...",2020-03-28,Other Policy Not Listed,Provincial/State Governm,https://www.nytimes.com/2020/03/31/world/asia/...,30000
3,3,404.0,Relaxation in the measured lockdown policies i...,2020-03-29,Other Policy Not Listed,Provincial/State Governm,https://reliefweb.int/report/afghanistan/afgha...,30000
4,4,405.0,"In Afghanistan, ""On 1 April, the Kabul Chief o...",2020-04-01,Other Policy Not Listed,NaN,https://reliefweb.int/report/afghanistan/afgha...,30000
...,...,...,...,...,...,...,...,...
16170,16171,21554.0,Zimbabwe has introduced mandatory screening fo...,2020-07-22,Health Testing,National Governm,https://twitter.com/edmnangagwa/status/1285955...,30185
16171,16172,21555.0,All vehicles used as a transport service in Zi...,2020-05-02,Hygien,"National Government,",http://www.veritaszim.net/sites/veritas_d/file...,30185
16172,16173,21556.0,Every individual must be temperature-tested an...,2020-05-02,Hygien,National Governm,http://www.veritaszim.net/sites/veritas_d/file...,30185
16173,16174,21558.0,When an employee tests positive for COVID-19 i...,2020-07-22,Hygien,"National Government,",https://www.veritaszim.net/sites/veritas_d/fil...,30185
16174,16175,21584.0,"In Zimbabwe, the Zimbabwe International Trade ...",2020-03-17,Restrictions of Mass Gatherings,National Governm,https://iharare.com/independence-day-zitf-post...,30185

In [12]:
gov_response = gov_response.drop(columns = ['Unnamed: 0'])

In [13]:
gov_response = gov_response.dropna()

In [14]:
# take a look at dtypes
gov_response.dtypes

response_id          float64
gov_resp_desc         object
gov_resp_date         object
gov_resp_type         object
enforcer              object
gov_resp_link_src     object
country_id             int64
dtype: object

# SQL Alchemy #

In [15]:
from sqlalchemy import create_engine
import sqlite3
# from secrets import username, password

engine = create_engine(f'postgresql://{username}:{password}@localhost:5432/Happiness_db')
conn=engine.connect()


un_govt.to_sql(name='un_govt',con=engine, if_exists='append',index=False)
world_happiness.to_sql(name='world_happiness',con=engine, if_exists='append',index=False)
world_covid_data.to_sql(name='world_covid_data',con=engine, if_exists='append',index=False)
gov_response.to_sql(name='gov_response',con=engine, if_exists='append',index=False)

In [16]:
govt = pd.read_sql("SELECT * FROM un_govt", conn )
govt.head()

,response_id,country_id,gov_resp_date,gov_resp_desc,enforcer,gov_resp_type,gov_resp_link_src
0,300,30000,2020-03-06,"March 6, Afghanistan ""Measures have been taken...","Ministry/Department of Health,Other",Anti-Disinformation Measures,https://www.etilaatroz.com/94246/fears-rumors-...
1,402,30000,2020-03-26,"""On 26 March, the President of Afghanistan, As...",National Governm,Other Policy Not Listed,https://reliefweb.int/report/afghanistan/afgha...
2,403,30000,2020-03-28,"In Afghanistan's ""eastern province of Nangarha...",Provincial/State Governm,Other Policy Not Listed,https://www.nytimes.com/2020/03/31/world/asia/...
3,404,30000,2020-03-29,Relaxation in the measured lockdown policies i...,Provincial/State Governm,Other Policy Not Listed,https://reliefweb.int/report/afghanistan/afgha...
4,406,30000,2020-04-05,"The governor of Afghanistan's capital, Kabul, ...","National Government,Military,Provincial/State ...",Other Policy Not Listed,https://www.bbc.com/persian/afghanistan-52171203

In [17]:
world_hap = pd.read_sql("SELECT * FROM world_happiness" , conn )
world_hap

,country_id,year_2020,world_region,gdp_per_capita,happiness_score,social_support,healthy_life_expectancy,freedom_of_choice,generosity,perceptions_of_corruption
0,30000,2020-01-01,South Asia,7.462861,2.5669,0.470367,52.590000,0.396573,-0.096429,0.933687
1,30001,2020-01-01,Central and Eastern Europe,9.417931,4.8827,0.671070,68.708138,0.781994,-0.042309,0.896304
2,30002,2020-01-01,Middle East and North Africa,9.537965,5.0051,0.803385,65.905174,0.466611,-0.121105,0.735485
3,30003,2020-01-01,Latin America and Caribbean,9.810955,5.9747,0.900568,68.803802,0.831132,-0.194914,0.842010
4,30004,2020-01-01,Commonwealth of Independent States,9.100476,4.6768,0.757479,66.750656,0.712018,-0.138780,0.773545
...,...,...,...,...,...,...,...,...,...,...
131,30181,2020-01-01,Latin America and Caribbean,8.977794,5.0532,0.890408,66.505341,0.623278,-0.169091,0.837038
132,30182,2020-01-01,Southeast Asia,8.809546,5.3535,0.849987,67.952736,0.939593,-0.094533,0.796421
133,30183,2020-01-01,Middle East and North Africa,7.759683,3.5274,0.817981,56.727283,0.599920,-0.157735,0.800288
134,30184,2020-01-01,Sub-Saharan Africa,8.224720,3.7594,0.698824,55.299377,0.806500,0.078037,0.801290
135,30185,2020-01-01,Sub-Saharan Africa,7.865712,3.2992,0.763093,55.617260,0.711458,-0.072064,0.810237

In [18]:
world_covid = pd.read_sql("SELECT * FROM world_covid_data", conn )
world_covid

,covid_cases_id,country_id,date,new_cases,new_deaths,extreme_poverty,handwashing_facilities,covid_times_life_expectancy
0,30,30000,2020-02-24,1,0,0,38,65
1,31,30000,2020-09-22,22,1,0,38,65
2,32,30000,2020-09-21,30,3,0,38,65
3,33,30000,2020-09-20,125,4,0,38,65
4,34,30000,2020-09-19,22,0,0,38,65
...,...,...,...,...,...,...,...,...
41669,59829,30185,2020-06-20,0,0,21,37,61
41670,59830,30185,2020-06-19,16,0,21,37,61
41671,59831,30185,2020-06-18,62,0,21,37,61
41672,59832,30185,2020-08-09,74,2,21,37,61
41673,59833,30185,2020-12-31,242,3,21,37,61

In [19]:
gov_resp = pd.read_sql("SELECT * FROM gov_response", conn )
gov_resp

,response_id,country_id,gov_resp_date,gov_resp_desc,enforcer,gov_resp_type,gov_resp_link_src
0,300,30000,2020-03-06,"March 6, Afghanistan ""Measures have been taken...","Ministry/Department of Health,Other",Anti-Disinformation Measures,https://www.etilaatroz.com/94246/fears-rumors-...
1,402,30000,2020-03-26,"""On 26 March, the President of Afghanistan, As...",National Governm,Other Policy Not Listed,https://reliefweb.int/report/afghanistan/afgha...
2,403,30000,2020-03-28,"In Afghanistan's ""eastern province of Nangarha...",Provincial/State Governm,Other Policy Not Listed,https://www.nytimes.com/2020/03/31/world/asia/...
3,404,30000,2020-03-29,Relaxation in the measured lockdown policies i...,Provincial/State Governm,Other Policy Not Listed,https://reliefweb.int/report/afghanistan/afgha...
4,406,30000,2020-04-05,"The governor of Afghanistan's capital, Kabul, ...","National Government,Military,Provincial/State ...",Other Policy Not Listed,https://www.bbc.com/persian/afghanistan-52171203
...,...,...,...,...,...,...,...
16057,21552,30185,2020-08-20,Every hotel in Zimbabwe shall dedicate a room ...,National Governm,Health Resources,https://www.veritaszim.net/node/4387
16058,21555,30185,2020-05-02,All vehicles used as a transport service in Zi...,"National Government,",Hygien,http://www.veritaszim.net/sites/veritas_d/file...
16059,21556,30185,2020-05-02,Every individual must be temperature-tested an...,National Governm,Hygien,http://www.veritaszim.net/sites/veritas_d/file...
16060,21558,30185,2020-07-22,When an employee tests positive for COVID-19 i...,"National Government,",Hygien,https://www.veritaszim.net/sites/veritas_d/fil...
16061,21584,30185,2020-03-17,"In Zimbabwe, the Zimbabwe International Trade ...",National Governm,Restrictions of Mass Gatherings,https://iharare.com/independence-day-zitf-post...

In [20]:
conn.close()